# Generated by Django 5.1.4 on 2024-12-10 22:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='product',
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage (e.g., 15.00 for 15%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='item_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
