# Generated by Django 5.1.4 on 2024-12-12 18:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBill', '0002_remove_invoiceline_product_invoice_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='EasyBill.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['-invoice_date'], name='EasyBill_in_invoice_c41aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='EasyBill_in_status_84de31_idx'),
        ),
        migrations.DeleteModel(
            name='InvoiceLine',
        ),
    ]
