# Generated by Django 5.1.4 on 2024-12-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBill', '0004_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('PAID', 'paid'), ('UUNPAID', 'unpaid'), ('PENDING', 'pending')], default='PENDING', max_length=20),
        ),
    ]
