# Generated by Django 5.1.4 on 2024-12-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyBill', '0005_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('paid', 'paid'), ('unpaid', 'unpaid'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
